openapi: 3.0.1
info:
  title: CBSAPI
  version: v1
servers:
  - url: /
security:
  - default: []
paths:
  /get-account-by-cif:
    get:
      parameters:
        - name: customerID
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: depositType
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: ok
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}
x-wso2-api-key-header: ApiKey
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: true
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - '*'
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
x-wso2-production-endpoints:
  urls:
    - 'http://10.10.100.75:8080/partner/cbs/api'
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - 'http://10.10.100.75:8080/partner/cbs/api'
  type: http
x-wso2-basePath: /cbs/v1
x-wso2-transports:
  - http
  - https
x-wso2-application-security:
  security-types:
    - oauth2
  optional: false
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300